In [1]:
import numpy as np
import pandas as pd

In [4]:
# show version
print(pd.__version__)
print(pd.show_versions(as_json = True))

0.23.4
{'system': {'commit': None, 'python': '3.7.0.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'None', 'LOCALE': 'None.None'}, 'dependencies': {'pandas': '0.23.4', 'pytest': '3.8.0', 'pip': '21.2.4', 'setuptools': '40.2.0', 'Cython': '0.28.5', 'numpy': '1.18.2', 'scipy': '1.1.0', 'pyarrow': None, 'xarray': None, 'IPython': '6.5.0', 'sphinx': '1.7.9', 'patsy': '0.5.0', 'dateutil': '2.7.3', 'pytz': '2018.5', 'blosc': None, 'bottleneck': '1.2.1', 'tables': '3.4.4', 'numexpr': '2.6.8', 'feather': None, 'matplotlib': '2.2.3', 'openpyxl': '2.5.6', 'xlrd': '1.1.0', 'xlwt': '1.3.0', 'xlsxwriter': '1.1.0', 'lxml': '4.2.5', 'bs4': '4.6.3', 'html5lib': '1.0.1', 'sqlalchemy': '1.2.11', 'pymysql': None, 'psycopg2': None, 'jinja2': '2.10', 's3fs': None, 'fastparquet': None, 'pandas_gbq': None, 'pandas_datareader': None}}
None


In [2]:
# create a series
mylist = list('abcedfghijklmnopqrstuvwxyz')  # list
myarr = np.arange(26)  # numpy array
mydict = dict(zip(mylist, myarr))  # dict
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(mylist)
print(myarr)
print(mydict)
print(ser1.head())
print(ser2.head())
print(ser3.head())

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
{'a': 0, 'b': 1, 'c': 2, 'e': 3, 'd': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}
0    a
1    b
2    c
3    e
4    d
dtype: object
0    0
1    1
2    2
3    3
4    4
dtype: int32
a    0
b    1
c    2
e    3
d    4
dtype: int64


In [21]:
# convert index to column
df = ser3.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [25]:
# combine series
df = pd.concat([ser1, ser2], axis = 1)
print(df.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


In [4]:
# 5. assign name to index
ser1.name = 'alphabets'
ser1.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [3]:
# minus
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [7]:
# 7.not common to both series
ser_u = pd.Series(np.union1d(ser1, ser2))
ser_i = pd.Series(np.intersect1d(ser1, ser2))
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [5]:
# percentile
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25)) # random.normal(loc=0.0, scale=1.0, size=None)
np.percentile(ser, q = [0,25,50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [8]:
# frequency count
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
# randint(upper_limit, size) as index, then take item from 'abcdefgh'
ser.value_counts()

e    6
b    6
h    5
d    5
g    3
c    3
a    1
f    1
dtype: int64

In [17]:
# keep top2 frequent value, and replce the everything else as other
state = np.random.RandomState(100)
ser = pd.Series(state.randint(1, 5, [12]))
ser.value_counts()
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object

In [23]:
# how to bin a numeric series to 10 groups of equal size
ser = pd.Series(np.random.random(20)) # [0, 1)
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1],\
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])

0      2nd
1      1st
2      3rd
3      7th
4      2nd
5      9th
6      5th
7      3rd
8      4th
9      9th
10     8th
11    10th
12     4th
13     5th
14     6th
15     1st
16     7th
17     6th
18     8th
19    10th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [26]:
ser = pd.Series(np.random.randint(1, 10, 35))
print(ser.values.reshape(7,  5))
print(pd.DataFrame(ser.values.reshape(7,  5)))

[[8 8 9 7 8]
 [6 5 9 8 2]
 [8 1 3 6 3]
 [7 4 9 9 3]
 [3 7 2 3 2]
 [6 4 1 7 1]
 [2 8 8 1 5]]
   0  1  2  3  4
0  8  8  9  7  8
1  6  5  9  8  2
2  8  1  3  6  3
3  7  4  9  9  3
4  3  7  2  3  2
5  6  4  1  7  1
6  2  8  8  1  5


In [27]:
# the position of numbers that are multiples of 3
ser = pd.Series(np.random.randint(1, 10, 7))
np.argwhere(ser % 3 == 0) # given a condition, return the index of array

array([[2],
       [4]], dtype=int64)

In [29]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser.take(pos) # given a index, return the value

0     a
4     e
8     i
14    o
20    u
dtype: object

In [31]:
# stack two series vertically and horizontally
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
# vertical
ser1.append(ser2)
# horizontal
pd.concat([ser1, ser2], axis = 1)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [39]:
# the position of series a in another series b
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
# [np.where(i == ser1)[0].tolist()[0] for i in ser2]
[pd.Index(ser1).get_loc(i) for i in ser2] # pd.Index used for indexing

[5, 4, 0, 8]

In [40]:
# MSE
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
# Solution
np.mean((truth-pred)**2)

0.3326742483549697

In [48]:
# convert the first character of each element in a series to uppercase
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
pd.Series([i.title() for i in ser])
ser.map(lambda x:x.title())
ser.map(lambda x:x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [52]:
# the length of each character
[len(i) for i in ser]
ser.map(lambda x:len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [56]:
# difference
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
ser.diff().tolist()

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [58]:
# date string to timeseries
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [61]:
# day of month, week number, day of year and day of week
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))
print("Date ", ser_ts.dt.day.tolist()) # day of month
print("week number ", ser_ts.dt.weekofyear.tolist())
print("day number of year ", ser_ts.dt.dayofyear.tolist())
print("day of week ", ser_ts.dt.weekday_name.tolist())

Date  [1, 2, 3, 4, 5, 6]
week number  [53, 5, 9, 14, 19, 23]
day number of year  [1, 33, 63, 94, 125, 157]
day of week  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [68]:
# convert year-month string to dates corresponding to the 4th day of the month
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser_ts = pd.to_datetime(ser)
ser_str = ser_ts.dt.year.astype(str) + '-' + ser_ts.dt.month.astype(str) + '-04'
[parse(i).strftime('%Y-%m-%d') for i in ser_str]

ser.map(lambda x:parse('04' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [71]:
# filter words that contain atleast 2 vowels
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(ser[mask])
print(mask)

0     Apple
1    Orange
4     Money
dtype: object
0     True
1     True
2    False
3    False
4     True
dtype: bool


In [75]:
#  filter valid emails
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re
mask = emails.map(lambda x:bool(re.match(pattern, x)))
emails[mask]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [78]:
# the mean of a series grouped by another series
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weight = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
weight.groupby(fruit).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'apple', 'carrot', 'banana', 'carrot', 'carrot', 'apple', 'banana', 'banana', 'banana']


apple     4.50
banana    7.75
carrot    3.75
dtype: float64

In [79]:
# 27. compute the euclidean distance between two series
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution 
sum((p - q)**2)**.5

# Solution (using func)
np.linalg.norm(p-q)

18.16590212458495

In [11]:
# find all the local maxima (or peaks) in a numeric series
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
dd = np.diff(np.sign(np.diff(ser)))
np.where(dd == -2)[0] + 1

array([1, 5, 7], dtype=int64)

In [21]:
# replace missing spaces in a string with the least frequent character
my_str = 'dbc deb abed gade'
least_freq = pd.Series(list(my_str)).value_counts().index[-1]
"".join(my_str.replace(' ', least_freq))

'dbccdebcabedcgade'

In [26]:
# TimeSeries
pd.Series(np.random.randint(1, 10, 10),\
         pd.date_range('2000-01-01', periods = 10, freq = 'W-SAT'))

2000-01-01    2
2000-01-08    7
2000-01-15    7
2000-01-22    2
2000-01-29    3
2000-02-05    4
2000-02-12    7
2000-02-19    5
2000-02-26    6
2000-03-04    8
Freq: W-SAT, dtype: int32

In [29]:
# fill an intermittent time series so all missing dates show up with values of previous non-missing date
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser.resample('D').ffill() # fill with previous value. 'D' meadns day
ser.resample('D').bfill()  # fill with next value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     NaN
2000-01-08     NaN
Freq: D, dtype: float64

In [36]:
# autocorrelations of a numeric series
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
[ser.autocorr(i) for i in range(11)] # The Pearson correlation between self and self.shift(lag).
# i means lag

[0.9999999999999999,
 0.29893747352226807,
 0.22889964858082074,
 0.2605165572777151,
 -0.016689052597570222,
 0.42982644330923975,
 0.5439978086495478,
 0.4986447175572082,
 0.289570581689875,
 0.3746497010081732,
 0.20265888106336585]

In [37]:
#  import only every nth row from a csv file to create a dataframe
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
df2.head()

age       b  chas     crim     dis  indus  lstat  medv    nox  ptratio  \
0    65.2  396.90   0.0  0.00632  4.0900   2.31   4.98  24.0  0.538     15.3   
50   45.7  395.56   0.0  0.08873  6.8147   5.64  13.45  19.7  0.439     16.8   
100  79.9  394.76   0.0  0.14866  2.7778   8.56   9.42  27.5  0.520     20.9   
150  97.3  372.80   0.0  1.65660  1.6180  19.58  14.10  21.5  0.871     14.7   
200  13.9  384.30   0.0  0.01778  7.6534   1.47   4.45  32.9  0.403     17.0   

     rad     rm    tax    zn  
0    1.0  6.575  296.0  18.0  
50   4.0  5.963  243.0  21.0  
100  5.0  6.727  384.0   0.0  
150  5.0  6.122  403.0   0.0  
200  3.0  7.135  402.0  95.0

In [39]:
# change column values when importing csv to a dataframe
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters = {'medv': lambda x: 'High' if float(x) > 25 else 'low'})
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   low  
1  396.90   9.14   low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High

In [40]:
# import only specified columns from a csv file
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
df.head()

crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

In [48]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# how many columns under each dtype
print(df.get_dtype_counts())
print(df.dtypes.value_counts())

# summary statistics
df_stats = df.describe()

# numpy array 
df_arr = df.values
print(df_arr)

# list
df_list = df.values.tolist()
print('-----------------')
print(df_list)

float64    18
object      9
dtype: int64
float64    18
object      9
dtype: int64
[['Acura' 'Integra' 'Small' ... 2705.0 'non-USA' 'Acura Integra']
 [nan 'Legend' 'Midsize' ... 3560.0 'non-USA' 'Acura Legend']
 ['Audi' '90' 'Compact' ... 3375.0 'non-USA' 'Audi 90']
 ...
 ['Volkswagen' 'Corrado' 'Sporty' ... 2810.0 'non-USA'
  'Volkswagen Corrado']
 ['Volvo' '240' 'Compact' ... 2985.0 'non-USA' 'Volvo 240']
 [nan '850' 'Midsize' ... 3245.0 'non-USA' 'Volvo 850']]
-----------------
[['Acura', 'Integra', 'Small', 12.9, 15.9, 18.8, 25.0, 31.0, 'None', 'Front', '4', 1.8, 140.0, 6300.0, 2890.0, 'Yes', 13.2, 5.0, 177.0, 102.0, 68.0, 37.0, 26.5, nan, 2705.0, 'non-USA', 'Acura Integra'], [nan, 'Legend', 'Midsize', 29.2, 33.9, 38.7, 18.0, 25.0, 'Driver & Passenger', 'Front', '6', 3.2, 200.0, 5500.0, 2335.0, 'Yes', 18.0, 5.0, 195.0, 115.0, 71.0, 38.0, 30.0, 15.0, 3560.0, 'non-USA', 'Acura Legend'], ['Audi', '90', 'Compact', 25.9, 29.1, 32.3, 20.0, 26.0, 'Driver only', 'Front', '6', 2.8, 172.0, 55

In [ ]:
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

In [53]:
# rename
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.rename(columns = {'Type':'CarType'})
# df.columns.values[2] = 'CarType'

df.columns = df.columns.map(lambda x:x.replace('.', '_'))

In [54]:
# check missing values
df.isnull().values.any()

True

In [57]:
# count the number of missing values in each column
df.isnull().sum()
# df.apply(lambda x: x.isnull().sum())

Manufacturer           4
Model                  1
Type                   3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [59]:
# replace missing values of multiple numeric columns with the mean
df_out = df[['Min_Price', 'Max_Price']].apply(lambda x: x.fillna(x.mean()))
df_out.head()

Min_Price  Max_Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

In [65]:
d = {'Min_Price': np.nanmean, 'Max_Price': np.nanmedian}
df[['Min_Price', 'Max_Price']].apply(lambda x: x.fillna(d[x.name](x))).head()

Min_Price  Max_Price
0  12.900000      18.80
1  29.200000      38.70
2  25.900000      32.30
3  17.118605      44.60
4  17.118605      19.15

In [69]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
# Solution
type(df[['a']])

pandas.core.frame.DataFrame

In [ ]:
# change order
df[('cbade')]
df[sorted(df.columns)]
df.sort_index(axis = 1, ascending = False, inplace = True)

In [70]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]

compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]

display.chop_threshold : float or None
    if set to a float value, all float values smaller then the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]

display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]

display.column_space No description available.
    [default: 12] [currently: 12]

display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]

display.date_year

In [71]:
# format: decimal
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
print(df)

df.round(4)
df.apply(lambda x: '%.4f' % x, axis = 1)

         random
0  3.285413e-04
1  1.753376e-07
2  1.472144e-06
3  4.921409e-05


In [73]:
# format: percentile
df.style.format({'random':'{0:.2%}'.format})

In [74]:
# filter nth row
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.iloc[::20,  :][['Model', 'Type']]

Model     Type
0   Integra    Small
20  LeBaron  Compact
40  Prelude   Sporty
60   Cougar  Midsize
80   Loyale    Small

In [3]:
# 50. create a primary key index by combining relevant columns
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)
print(df.head())

True
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN


In [5]:
# get the row number of the nth largest value in a column
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
n = 5
df['a'].argsort()[::-1][n]

7

In [ ]:
# find the position of the 2nd largest value greater than the mean.
np.argwhere(ser > ser.mean())[1]

In [8]:
# get the last n rows of a dataframe with row sum > 100
df = pd.DataFrame(np.random.randint(10, 40,60).reshape(-1, 4))
rowsums = df.apply(np.sum, axis = 1)
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
last_two_rows

0   1   2   3
12  15  32  21  37
13  26  33  30  16

In [14]:
# jpmorgan
a = 123456
b = list(str(a))
b

c = [int(i) for i in b]
c

d = list(range(-len(c), 0, 2))
d

for i in d:
    c[i] = 2*c[i]
c

e = [str(i) for i in c]
e

f = ''.join(e)

g = list(f)
g

result = 0
for i in g:
    result += int(i)
result

['1', '2', '3', '4', '5', '6']

In [3]:
# swap two rows
df = pd.DataFrame(np.arange(25).reshape(5, -1))

def swap_rows(df, i1,i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :]
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

swap_rows(df, 1, 2)

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [4]:
# reverse the rows of a dataframe
df.iloc[::-1, :]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2   5   6   7   8   9
1  10  11  12  13  14
0   0   1   2   3   4

In [6]:
# one hot encoding
df = pd.DataFrame(np.arange(25).reshape(5, -1), columns = list('abcde'))
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis = 1)
df_onehot

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [15]:
 # Which column contains the highest number of row-wise maximum values?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df.apply(np.argmax, axis = 1).value_counts().index[0]

C:\Users\lenovo\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:61: FutureWarning: 'argmax' is deprecated, use 'idxmax' instead. The behavior of 'argmax'
will be corrected to return the positional maximum in the future.
Use 'series.values.argmax' to get the position of the maximum now.
  return bound(*args, **kwds)


3

In [16]:
# max possible corr between each columns
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

abs_corr = np.abs(df.corr())
max_corr = abs_corr.apply(lambda x: sorted(x)[-2])
np.round(max_corr.tolist(), 2)

p   q   r   s   t   u   v   w   x   y
a  36  25   7  96  24  97  63  80  81  19
b  98  82  66  35  61  87  99  55  59  11
c  27  52  14  53  84  55  40  44  50  65
d  39  17  59  41  27  47   1  99  58  18
e  54  22  48  33  43  67  15  98  40  41
f  11  39   8  59  25  62  24  75  31  39
g  97  59  86  82  32  63  46  26  78  60
h  52  54  98  69  17  67  79  51  53  10

In [ ]:
# min by max
min_by_max = df.apply(lambda x: x.min(x)/x.max(x), axis = 1)

In [19]:
# the penultimate value in each row
out = df.apply(lambda x: x.sort_values().unique()[-2], axis = 1)
df['penultimate'] = out

In [ ]:
# normalize all columns
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
out2 = df.apply(lambda x: (x.max() - x)/(x.max() - x.min())).round(2)

In [ ]:
# corr with suceeding row
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

In [ ]:
# replace both diagonals of dataframe with 0
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

In [ ]:
# get particular group
df.groupby('col').get_group('apple')

In [ ]:
# the n’th largest value of a column when grouped by another column
df['taste'].groupby(df.fruit).get_group('banana').sort_values().iloc[-2]

In [ ]:
# compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)
df.groupby('fruit', as_index = False)['price'].mean()

In [ ]:
# join two dataframes by 2 columns so they have only the common rows
pd.merge(df1, df2, how = 'inner', left_on = ['a', 'b'], right_on = ['c', 'd'], suffixes = ['_left', '_right'])

In [23]:
# remove rows from a dataframe that are present in another dataframe
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})

df1[~df1.isin(df2).all(axis = 1)]

fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8

In [ ]:
# get the positions where values of two columns match
np.where(df.fruit1 == df.fruit2)

In [ ]:
# create lags and leads of a column in a dataframe
df['a_lag'] = df['a'].shift(1)
df['a_lag'] = df['a'].shift(-1)

In [9]:
# get the frequency of unique values in the entire dataframe
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

pd.value_counts(df.values.ravel())

2    6
6    3
5    3
8    2
7    2
9    1
4    1
3    1
1    1
dtype: int64

In [5]:
import pandas as pd
import numpy as np

In [17]:
# split a text column into two separate columns
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns = ['row'])

df_out = df.row.str.split(',|    ', expand = True)
df_out

# first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
df_out

0 STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka